# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66abbb88ed5b317e9350e24e3647d646988fb92e372bf97aa2a03ecc59273d09b301b79f593ca2f645d33ed137c912b22313f94665c134aed6ff794b3a581b0c

test:
  secret_key_base: 3d416ed1a8cd44d7cbc320b1d90a18ffdc1429999a20a79c93aec3d5f3d4d3009545609bd8839b36d1c02f0ba91737ec0921db28fa4987e09d83016dab304019

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
